<?php

namespace VegeWildBundle\Repository;

/**
 * SugarRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SugarRecipeRepository extends \Doctrine\ORM\EntityRepository
{
}
